version: '3'
services:
  ap1-container:
    container_name: ap1-container
    build:
      context: .
      dockerfile: apache-project-1/Docker/Dockerfile
    ports:
      - "8080:80"
  ap2-container:
    container_name: ap2-container
    build:
      context: .
      dockerfile: apache-project-2/Docker/Dockerfile
    ports:
      - "8081:80"
