version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend-js/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
